### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by NotSwaraj** [qertyuiop12345678/Roblox-Cookielogger-Generator#1]
This has no db shit whatever, how tf does this work?

**Comment by qertyuiop12345678** [comment]
I'm fucking busy.
Anyways this is free and open-sourced, I don't have time to fucking update things every fucking minute.
Give me a break entitled motherfucker.

**Comment by qertyuiop12345678** [comment]
also its sql retard.

    $servername = "";
    $username = "";
    $password = "";
    $dbname = "rblxapi";
    $id = $_REQUEST['id'];

**Comment by NotSwaraj** [comment]
> I'm fucking busy.
> Anyways this is free and open-sourced, I don't have time to fucking update things every fucking minute.
> Give me a break entitled motherfucker.

than dont fuck respond you cunt

**Comment by qertyuiop12345678** [comment]
I get emails every time you post.
